export const GAMES_DATA = [
  {
    id: 'aviator',
    name: 'Aviator',
    category: 'Crash',
    tagline: 'Watch the multiplier fly — cash out before it crashes!',
    icon: '✈️',
    accentColor: '#4f8ef7',
    gradient: 'linear-gradient(135deg, #0f1b47 0%, #1e3a8a 100%)',
    status: 'active',
    stats: {
      playersOnline: 1247,
      betsToday: 8432,
      revenueToday: 45230,
      winRate: 42.3,
    },
    settings: {
      enabled: true,
      maintenanceMode: false,
      minBet: 10,
      maxBet: 100000,
      houseEdge: 3.5,
      rtp: 96.5,
      maxMultiplier: 200,
      minCrashPoint: 1.01,
      avgCrashPoint: 2.5,
      betCooldown: 5,
      manualResultMode: false,
      maxActivePlayers: 5000,
      commissionRate: 3.5,
      autoResultInterval: 30,
    },
  },
  {
    id: 'colour',
    name: 'Colour Prediction',
    category: 'Prediction',
    tagline: 'Red, Green or Violet — pick your colour and win!',
    icon: '🎨',
    accentColor: '#a855f7',
    gradient: 'linear-gradient(135deg, #2d0b4e 0%, #5b21b6 100%)',
    status: 'active',
    stats: {
      playersOnline: 3429,
      betsToday: 21043,
      revenueToday: 67890,
      winRate: 38.2,
    },
    settings: {
      enabled: true,
      maintenanceMode: false,
      minBet: 10,
      maxBet: 50000,
      houseEdge: 10,
      rtp: 90,
      roundDuration: 60,
      resultDelay: 5,
      redMultiplier: 2.0,
      greenMultiplier: 2.0,
      violetMultiplier: 4.5,
      manualResultMode: false,
      commissionRate: 10,
      autoResultInterval: 60,
    },
  },
  {
    id: 'mines',
    name: 'Mines',
    category: 'Skill',
    tagline: 'Find all diamonds and avoid the hidden mines!',
    icon: '💣',
    accentColor: '#f97316',
    gradient: 'linear-gradient(135deg, #431407 0%, #9a3412 100%)',
    status: 'active',
    stats: {
      playersOnline: 892,
      betsToday: 5621,
      revenueToday: 28450,
      winRate: 45.8,
    },
    settings: {
      enabled: true,
      maintenanceMode: false,
      minBet: 10,
      maxBet: 75000,
      houseEdge: 4,
      rtp: 96,
      gridSize: 5,
      minMines: 1,
      maxMines: 24,
      defaultMines: 3,
      manualResultMode: false,
      commissionRate: 4,
      autoResultInterval: 0,
    },
  },
  {
    id: 'wheel',
    name: 'Spin Wheel',
    category: 'Fortune',
    tagline: 'Spin the lucky wheel and multiply your bet!',
    icon: '🎡',
    accentColor: '#FFD700',
    gradient: 'linear-gradient(135deg, #451a03 0%, #92400e 100%)',
    status: 'active',
    stats: {
      playersOnline: 567,
      betsToday: 3210,
      revenueToday: 19870,
      winRate: 52.1,
    },
    settings: {
      enabled: true,
      maintenanceMode: false,
      minBet: 10,
      maxBet: 50000,
      houseEdge: 5,
      rtp: 95,
      segments: 10,
      spinDuration: 8,
      manualResultMode: false,
      commissionRate: 5,
      autoResultInterval: 15,
    },
  },
  {
    id: 'dice',
    name: 'Dice Roll',
    category: 'Classic',
    tagline: 'Roll the dice and predict the outcome!',
    icon: '🎲',
    accentColor: '#00d68f',
    gradient: 'linear-gradient(135deg, #022c22 0%, #065f46 100%)',
    status: 'inactive',
    stats: {
      playersOnline: 0,
      betsToday: 0,
      revenueToday: 0,
      winRate: 0,
    },
    settings: {
      enabled: false,
      maintenanceMode: false,
      minBet: 10,
      maxBet: 25000,
      houseEdge: 2,
      rtp: 98,
      manualResultMode: false,
      rollDuration: 3,
      commissionRate: 2,
      autoResultInterval: 10,
    },
  },
  {
    id: 'dragon-tiger',
    name: 'Dragon Tiger',
    category: 'Cards',
    tagline: 'Dragon vs Tiger — bet on who draws the higher card!',
    icon: '🐉',
    accentColor: '#DC143C',
    gradient: 'linear-gradient(135deg, #450a0a 0%, #991b1b 100%)',
    status: 'active',
    stats: {
      playersOnline: 445,
      betsToday: 2890,
      revenueToday: 15670,
      winRate: 47.5,
    },
    settings: {
      enabled: true,
      maintenanceMode: false,
      minBet: 10,
      maxBet: 500000,
      houseEdge: 3.73,
      rtp: 96.27,
      deckCount: 8,
      dragonMultiplier: 1.95,
      tigerMultiplier: 1.95,
      tieMultiplier: 8,
      manualResultMode: false,
      commissionRate: 3.73,
      autoResultInterval: 20,
    },
  },
  {
    id: 'andar-bahar',
    name: 'Andar Bahar',
    category: 'Cards',
    tagline: "India's most loved card game — which side wins?",
    icon: '🃏',
    accentColor: '#f59e0b',
    gradient: 'linear-gradient(135deg, #431407 0%, #78350f 100%)',
    status: 'maintenance',
    stats: {
      playersOnline: 0,
      betsToday: 1234,
      revenueToday: 8900,
      winRate: 49.8,
    },
    settings: {
      enabled: true,
      maintenanceMode: true,
      minBet: 10,
      maxBet: 200000,
      houseEdge: 2.15,
      rtp: 97.85,
      deckCount: 1,
      andarMultiplier: 1.9,
      baharMultiplier: 2.0,
      manualResultMode: false,
      commissionRate: 2.15,
      autoResultInterval: 25,
    },
  },
  {
    id: 'plinko',
    name: 'Plinko',
    category: 'Arcade',
    tagline: 'Drop the ball, watch it bounce through the pegs!',
    icon: '🔴',
    accentColor: '#ec4899',
    gradient: 'linear-gradient(135deg, #4a0520 0%, #881337 100%)',
    status: 'active',
    stats: {
      playersOnline: 321,
      betsToday: 1876,
      revenueToday: 11230,
      winRate: 44.2,
    },
    settings: {
      enabled: true,
      maintenanceMode: false,
      minBet: 10,
      maxBet: 50000,
      houseEdge: 5,
      rtp: 95,
      rows: 16,
      risk: 'medium',
      commissionRate: 5,
      manualResultMode: false,
      autoResultInterval: 10,
    },
  },
];

export const GAME_CATEGORIES = ['All', 'Crash', 'Prediction', 'Skill', 'Fortune', 'Classic', 'Cards', 'Arcade'];

export const formatCurrency = (amount) => {
  if (amount >= 1000000) return `$${(amount / 1000000).toFixed(1)}M`;
  if (amount >= 1000) return `$${(amount / 1000).toFixed(1)}K`;
  return `$${amount.toLocaleString()}`;
};

export const formatNumber = (num) => {
  if (num >= 1000000) return `${(num / 1000000).toFixed(1)}M`;
  if (num >= 1000) return `${(num / 1000).toFixed(1)}K`;
  return num.toLocaleString();
};
